apiVersion: v1
kind: Secret
metadata:
  name: clearflow-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clearflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  oracle-password: {{ .Values.secrets.oraclePassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  artemis-password: {{ .Values.secrets.artemisPassword | quote }}
  openrouter-api-key: {{ .Values.secrets.openrouterApiKey | quote }}
  vault-token: {{ .Values.secrets.vaultToken | quote }}
