apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: DS_PROMETHEUS
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: DS_JAEGER

  - name: Jaeger
    type: jaeger
    uid: DS_JAEGER
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: DS_ELASTICSEARCH
        filterByTraceID: true

  - name: Elasticsearch
    type: elasticsearch
    uid: DS_ELASTICSEARCH
    access: proxy
    url: http://elasticsearch:9200
    isDefault: false
    jsonData:
      index: clearflow-*
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
