input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  mutate {
    remove_field => ["debtorIban", "creditorIban", "pan", "cardNumber"]
  }
  ruby {
    code => "event.set('pci_masking', 'applied')"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "clearflow-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
